# Generated by Django 4.2.7 on 2025-07-30 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='题号')),
                ('question_text', models.TextField(verbose_name='题干')),
                ('options', models.JSONField(verbose_name='选项')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题')], max_length=10, verbose_name='题目类型')),
                ('correct_answers', models.JSONField(verbose_name='正确答案')),
                ('explanation', models.TextField(blank=True, verbose_name='答案解析')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目集合标题')),
                ('questions_file', models.FileField(upload_to='questions/', verbose_name='题目文件')),
                ('answers_file', models.FileField(upload_to='answers/', verbose_name='答案解析文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '题目集合',
                'verbose_name_plural': '题目集合',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answers', models.JSONField(verbose_name='用户答案')),
                ('is_correct', models.BooleanField(verbose_name='是否正确')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='questions.question')),
            ],
            options={
                'verbose_name': '用户答案',
                'verbose_name_plural': '用户答案',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.questionset'),
        ),
    ]
